//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final_NF.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_orderEntities : DbContext
    {
        public db_orderEntities()
            : base("name=db_orderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_authentication> tbl_authentication { get; set; }
        public virtual DbSet<tbl_authorization> tbl_authorization { get; set; }
        public virtual DbSet<tbl_category> tbl_category { get; set; }
        public virtual DbSet<tbl_member> tbl_member { get; set; }
        public virtual DbSet<tbl_order> tbl_order { get; set; }
        public virtual DbSet<tbl_order_detail> tbl_order_detail { get; set; }
        public virtual DbSet<tbl_order_item> tbl_order_item { get; set; }
        public virtual DbSet<tbl_product> tbl_product { get; set; }
    }
}
