//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final_NF.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_authorization
    {
        public int id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public int id_authen { get; set; }
        public int active { get; set; }
    
        public virtual tbl_authentication tbl_authentication { get; set; }
    }
}
