//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Final_NF.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_product()
        {
            this.tbl_order_detail = new HashSet<tbl_order_detail>();
            this.tbl_order_item = new HashSet<tbl_order_item>();
        }
    
        public int product_id { get; set; }
        public string name { get; set; }
        public Nullable<int> stock_quantity { get; set; }
        public decimal price { get; set; }
        public string image_url { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_detail> tbl_order_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_order_item> tbl_order_item { get; set; }
    }
}
